on:
  workflow_dispatch

name: test

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest}
          #- {os: windows-latest}
          - {os: ubuntu-latest}

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2

    - name: Install macOS system dependencies
      if: runner.os == 'macOS'
      run: brew install gdal proj

    - name: Install Linux system dependencies
      if: runner.os == 'Linux'
      run: sudo apt install libgdal-dev libgeos-dev libproj-dev

    - name: Install packages
      run: R -e 'install.packages("terra")'

    - name: Test script
      run: Rscript test.R
