on:
  workflow_dispatch

name: test

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2

    - name: Install spatial dependencies
      run: brew install gdal proj

    - name: Install packages
      run: R -e 'install.packages("terra")'

    - name: Test script
      run: Rscript test.R
